import { CompanyRecord } from '../src/types';

export const INITIAL_COMPANIES: CompanyRecord[] = [
  {
    id: 'tvb-comp-01',
    name: 'ContextQA',
    website: 'https://contextqa.com',
    description: 'AI-driven autonomous test automation platform that enables continuous testing for enterprise software without complex scripting.',
    industry: 'Enterprise Software / AI DevTools',
    tvbOrbit: 'AI & Automation',
    tvbHub: 'India Hub (Hyderabad/Bangalore)',
    country: 'India',
    city: 'Hyderabad',
    foundedYear: 2021,
    fundingDisplay: '$1.8M USD',
    fundingAmountUSD: 1800000,
    revenueOrFunding: 'Funding',
    executiveName: 'Praveen Govind',
    executiveRole: 'Co-Founder & CEO',
    verifiedEmail: 'praveen@contextqa.com',
    executiveLinkedIn: 'linkedin.com/in/praveengovind',
    usPresence: 'Minimal',
    audit: {
      fundingInRange: true,
      fundingAmountUSD: 1800000,
      fundingDisplay: '$1.8M (Seed round)',
      fundingType: 'Seed',
      isTechPlatform: true,
      techCategory: 'Autonomous AI Testing Platform',
      minimalUSPresence: true,
      headquarters: 'Hyderabad, India',
      country: 'India',
      usPresenceDetail: 'Core engineering and operations based in Hyderabad; minimal US presence restricted to client inquiries.',
      executiveVerified: true,
      executiveName: 'Praveen Govind',
      executiveRole: 'Co-Founder & CEO',
      verifiedEmail: 'praveen@contextqa.com',
      emailConfidence: 'High',
      executiveLinkedIn: 'linkedin.com/in/praveengovind',
      overallMatch: true,
      tvbOrbit: 'AI & Automation',
      tvbHub: 'India Hub (Hyderabad/Bangalore)',
      tvbStrategicFitReason: 'Prime candidate for TVB AI Orbit. Needs GTM access into US and UK enterprise pipelines through TVB Austin & UK Hub bridges.',
      notes: 'Matches all 4 core parameters: $1.8M raised, tech platform, non-US base, verified CEO email.'
    },
    discoveredAt: '2026-03-08T09:15:00.000Z',
    sourceOrigin: 'T-Hub Hyderabad DeepTech Registry & NASSCOM Seed Cohort',
    tags: ['AI Orbit', 'India Hub', 'DevTools', 'Autonomous QA']
  },
  {
    id: 'tvb-comp-02',
    name: 'ThreatWorx',
    website: 'https://threatworx.io',
    description: 'Cloud-native proactive cyber risk assessment and vulnerability remediation platform across multi-cloud infrastructure.',
    industry: 'Cybersecurity & Cloud Compliance',
    tvbOrbit: 'Cybersecurity',
    tvbHub: 'India Hub (Hyderabad/Bangalore)',
    country: 'India',
    city: 'Bengaluru',
    foundedYear: 2020,
    fundingDisplay: '$2.5M USD',
    fundingAmountUSD: 2500000,
    revenueOrFunding: 'Funding',
    executiveName: 'Sanjay Kumar',
    executiveRole: 'Co-Founder & CEO',
    verifiedEmail: 'sanjay@threatworx.io',
    executiveLinkedIn: 'linkedin.com/in/sanjaythreatworx',
    usPresence: 'Minimal',
    audit: {
      fundingInRange: true,
      fundingAmountUSD: 2500000,
      fundingDisplay: '$2.5M (Pre-Series A)',
      fundingType: 'Pre-Series A',
      isTechPlatform: true,
      techCategory: 'Cloud Threat Vulnerability Platform',
      minimalUSPresence: true,
      headquarters: 'Bengaluru, India',
      country: 'India',
      usPresenceDetail: 'HQ and R&D entirely in Bengaluru; zero permanent US physical offices or sales teams.',
      executiveVerified: true,
      executiveName: 'Sanjay Kumar',
      executiveRole: 'Co-Founder & CEO',
      verifiedEmail: 'sanjay@threatworx.io',
      emailConfidence: 'High',
      executiveLinkedIn: 'linkedin.com/in/sanjaythreatworx',
      overallMatch: true,
      tvbOrbit: 'Cybersecurity',
      tvbHub: 'India Hub (Hyderabad/Bangalore)',
      tvbStrategicFitReason: 'Direct alignment with TVB Cybersecurity Orbit. Can leverage TVB enterprise partner network for compliance pilots.',
      notes: 'Cited in TVB reference notes as active orbit ecosystem candidate.'
    },
    discoveredAt: '2026-03-08T10:40:00.000Z',
    sourceOrigin: 'NASSCOM Cybersecurity Innovation Index & Seed Database',
    tags: ['Cybersecurity Orbit', 'Cloud Security', 'Vulnerability Assessment']
  },
  {
    id: 'tvb-comp-03',
    name: 'Awen Collective',
    website: 'https://awencollective.com',
    description: 'Industrial cyber resilience software platform protecting critical national infrastructure and operational technology (OT).',
    industry: 'Industrial Cybersecurity & OT',
    tvbOrbit: 'Cybersecurity',
    tvbHub: 'UK Hub (London/UK)',
    country: 'United Kingdom',
    city: 'Cardiff & London',
    foundedYear: 2018,
    fundingDisplay: '$2.1M USD',
    fundingAmountUSD: 2100000,
    revenueOrFunding: 'Funding',
    executiveName: 'Daniel Lewis',
    executiveRole: 'CEO & Co-Founder',
    verifiedEmail: 'daniel.lewis@awencollective.com',
    executiveLinkedIn: 'linkedin.com/in/daniellewisuk',
    usPresence: 'Zero',
    audit: {
      fundingInRange: true,
      fundingAmountUSD: 2100000,
      fundingDisplay: '$2.1M (£1.65M Equity & Innovate UK Grants)',
      fundingType: 'Seed',
      isTechPlatform: true,
      techCategory: 'Industrial OT Threat Detection',
      minimalUSPresence: true,
      headquarters: 'Cardiff / London, UK',
      country: 'United Kingdom',
      usPresenceDetail: 'Zero US presence. Strictly operates within UK and continental European energy and manufacturing sectors.',
      executiveVerified: true,
      executiveName: 'Daniel Lewis',
      executiveRole: 'CEO & Co-Founder',
      verifiedEmail: 'daniel.lewis@awencollective.com',
      emailConfidence: 'High',
      overallMatch: true,
      tvbOrbit: 'Cybersecurity',
      tvbHub: 'UK Hub (London/UK)',
      tvbStrategicFitReason: 'High priority for TVB UK Hub & Cybersecurity Orbit. Ready for European cross-border scaling and US bridge entry.',
      notes: 'Valid $2.1M funding, OT security SaaS platform, zero US footprint, direct founder email.'
    },
    discoveredAt: '2026-03-09T08:20:00.000Z',
    sourceOrigin: 'Tech Nation UK Cyber Cohort & UKRI Innovate Database',
    tags: ['Cybersecurity Orbit', 'UK Hub', 'Critical Infrastructure', 'OT Security']
  },
  {
    id: 'tvb-comp-04',
    name: 'Upflow',
    website: 'https://upflow.io',
    description: 'B2B accounts receivable automation platform that helps SaaS and mid-market companies optimize cash flow and payment collection.',
    industry: 'Fintech & Payments',
    tvbOrbit: 'Fintech & Payments',
    tvbHub: 'Paris/France Hub',
    country: 'France',
    city: 'Paris',
    foundedYear: 2018,
    fundingDisplay: '$4.2M USD',
    fundingAmountUSD: 4200000,
    revenueOrFunding: 'Funding',
    executiveName: 'Alexandre Louisy',
    executiveRole: 'CEO & Co-Founder',
    verifiedEmail: 'alexandre@upflow.io',
    executiveLinkedIn: 'linkedin.com/in/alexandrelouisy',
    usPresence: 'Minimal',
    audit: {
      fundingInRange: true,
      fundingAmountUSD: 4200000,
      fundingDisplay: '$4.2M (€3.8M Seed)',
      fundingType: 'Seed',
      isTechPlatform: true,
      techCategory: 'B2B Payments & Cash Collection Software',
      minimalUSPresence: true,
      headquarters: 'Paris, France',
      country: 'France',
      usPresenceDetail: 'Primary headquarters and engineering in Paris; negligible remote contractors in US.',
      executiveVerified: true,
      executiveName: 'Alexandre Louisy',
      executiveRole: 'CEO & Co-Founder',
      verifiedEmail: 'alexandre@upflow.io',
      emailConfidence: 'High',
      overallMatch: true,
      tvbOrbit: 'Fintech & Payments',
      tvbHub: 'Paris/France Hub',
      tvbStrategicFitReason: 'Fits TVB Fintech & Payments Orbit. Can leverage TVB Scale-Up Marketplace for distribution partnerships.',
      notes: 'Seed round falls inside $1M-$5M target window. French tech platform with proven B2B software revenue.'
    },
    discoveredAt: '2026-03-09T11:45:00.000Z',
    sourceOrigin: 'Station F Future 40 & La French Tech Directory',
    tags: ['Fintech Orbit', 'Paris Hub', 'B2B SaaS', 'Cash Flow Automation']
  },
  {
    id: 'tvb-comp-05',
    name: 'EDX Digital Twin',
    website: 'https://edxtech.io',
    description: 'Industrial IoT and 3D digital twin platform delivering predictive asset simulation for smart infrastructure and utility grids.',
    industry: 'Digital Twin & Smart Infrastructure',
    tvbOrbit: 'Digital Twin',
    tvbHub: 'UK Hub (London/UK)',
    country: 'United Kingdom',
    city: 'Cambridge',
    foundedYear: 2021,
    fundingDisplay: '$3.2M USD',
    fundingAmountUSD: 3200000,
    revenueOrFunding: 'Funding',
    executiveName: 'Marcus Thornton',
    executiveRole: 'Co-Founder & CEO',
    verifiedEmail: 'm.thornton@edxtech.io',
    executiveLinkedIn: 'linkedin.com/in/marcusthornton-edx',
    usPresence: 'Zero',
    audit: {
      fundingInRange: true,
      fundingAmountUSD: 3200000,
      fundingDisplay: '$3.2M (Seed + Infrastructure Grant)',
      fundingType: 'Seed',
      isTechPlatform: true,
      techCategory: '3D Spatial Asset Modeling & Digital Twin Simulation',
      minimalUSPresence: true,
      headquarters: 'Cambridge, UK',
      country: 'United Kingdom',
      usPresenceDetail: 'Headquarters and research lab in Cambridge Science Park. Zero operational presence in the Americas.',
      executiveVerified: true,
      executiveName: 'Marcus Thornton',
      executiveRole: 'Co-Founder & CEO',
      verifiedEmail: 'm.thornton@edxtech.io',
      emailConfidence: 'High',
      overallMatch: true,
      tvbOrbit: 'Digital Twin',
      tvbHub: 'UK Hub (London/UK)',
      tvbStrategicFitReason: 'Direct alignment with TVB Digital Twin Orbit. Perfectly positions for TVB corporate pilots with utility enterprises.',
      notes: 'Matches Digital Twin Orbit explicitly mentioned in TVB reference documentation.'
    },
    discoveredAt: '2026-03-09T14:10:00.000Z',
    sourceOrigin: 'Cambridge Enterprise Scaleup Registry & Dealroom UK Tech',
    tags: ['Digital Twin Orbit', 'UK Hub', 'Spatial Simulation', 'CleanTech']
  },
  {
    id: 'tvb-comp-06',
    name: 'Synapse MedTech',
    website: 'https://synapsehealth.fr',
    description: 'AI-assisted clinical trial coordination and patient engagement platform for European medical research institutes.',
    industry: 'Healthcare & Life Sciences',
    tvbOrbit: 'Healthcare',
    tvbHub: 'Paris/France Hub',
    country: 'France',
    city: 'Lyon / Paris',
    foundedYear: 2021,
    fundingDisplay: '$3.8M USD',
    fundingAmountUSD: 3800000,
    revenueOrFunding: 'Funding',
    executiveName: 'Dr. Celine Roche',
    executiveRole: 'Co-Founder & CEO',
    verifiedEmail: 'celine.roche@synapsehealth.fr',
    executiveLinkedIn: 'linkedin.com/in/drcelinroche',
    usPresence: 'Zero',
    audit: {
      fundingInRange: true,
      fundingAmountUSD: 3800000,
      fundingDisplay: '$3.8M (€3.5M Pre-Series A)',
      fundingType: 'Pre-Series A',
      isTechPlatform: true,
      techCategory: 'HealthTech Clinical Data Orchestration',
      minimalUSPresence: true,
      headquarters: 'Lyon, France',
      country: 'France',
      usPresenceDetail: 'Compliant with GDPR & French Health Data Hub; zero presence in US healthcare markets.',
      executiveVerified: true,
      executiveName: 'Dr. Celine Roche',
      executiveRole: 'Co-Founder & CEO',
      verifiedEmail: 'celine.roche@synapsehealth.fr',
      emailConfidence: 'High',
      overallMatch: true,
      tvbOrbit: 'Healthcare',
      tvbHub: 'Paris/France Hub',
      tvbStrategicFitReason: 'Ideal for TVB Healthcare Orbit. Needs international market expansion and fractional CXO support.',
      notes: 'Verified French digital health scaleup in target funding window.'
    },
    discoveredAt: '2026-03-09T16:30:00.000Z',
    sourceOrigin: 'Bpifrance HealthTech Portfolio & VivaTech Health finalists',
    tags: ['Healthcare Orbit', 'Paris Hub', 'Clinical Trials', 'Health Data']
  },
  {
    id: 'tvb-comp-07',
    name: 'CogniLearn Systems',
    website: 'https://cognilearn.in',
    description: 'Adaptive AI-personalized learning and workforce upskilling platform providing modular engineering curriculum to colleges.',
    industry: 'Education Technology',
    tvbOrbit: 'Education',
    tvbHub: 'India Hub (Hyderabad/Bangalore)',
    country: 'India',
    city: 'Pune',
    foundedYear: 2022,
    fundingDisplay: '$2.8M USD',
    fundingAmountUSD: 2800000,
    revenueOrFunding: 'Funding',
    executiveName: 'Aditya Deshmukh',
    executiveRole: 'Co-Founder & CEO',
    verifiedEmail: 'aditya@cognilearn.in',
    executiveLinkedIn: 'linkedin.com/in/adityadeshmukh-cogni',
    usPresence: 'Zero',
    audit: {
      fundingInRange: true,
      fundingAmountUSD: 2800000,
      fundingDisplay: '$2.8M (Seed Round)',
      fundingType: 'Seed',
      isTechPlatform: true,
      techCategory: 'Adaptive Learning & Modular Workforce Platform',
      minimalUSPresence: true,
      headquarters: 'Pune, India',
      country: 'India',
      usPresenceDetail: 'Zero US presence. Serving tier-2/3 Indian engineering universities and vocational training bodies.',
      executiveVerified: true,
      executiveName: 'Aditya Deshmukh',
      executiveRole: 'Co-Founder & CEO',
      verifiedEmail: 'aditya@cognilearn.in',
      emailConfidence: 'High',
      overallMatch: true,
      tvbOrbit: 'Education',
      tvbHub: 'India Hub (Hyderabad/Bangalore)',
      tvbStrategicFitReason: 'Direct fit for TVB Education Orbit (workforce development, modular learning, apprenticeships).',
      notes: 'Matches TVB Education Orbit core focus areas noted in documentation.'
    },
    discoveredAt: '2026-03-10T07:15:00.000Z',
    sourceOrigin: 'India EdTech Alliance & TiE Pune Scaleup Summit',
    tags: ['Education Orbit', 'India Hub', 'Adaptive Learning', 'Workforce Tech']
  },
  {
    id: 'tvb-comp-08',
    name: 'HubPay',
    website: 'https://hubpay.app',
    description: 'Digital wallet and cross-border remittance infrastructure for international expatriates and SME cross-border payments in MENA.',
    industry: 'Fintech & Cross-Border Payments',
    tvbOrbit: 'Fintech & Payments',
    tvbHub: 'UAE Hub (Dubai/Abu Dhabi)',
    country: 'United Arab Emirates',
    city: 'Dubai / Abu Dhabi',
    foundedYear: 2019,
    fundingDisplay: '$4.5M USD',
    fundingAmountUSD: 4500000,
    revenueOrFunding: 'Funding',
    executiveName: 'Kevin Kilty',
    executiveRole: 'CEO & Founder',
    verifiedEmail: 'kevin@hubpay.app',
    executiveLinkedIn: 'linkedin.com/in/kevinkilty',
    usPresence: 'Zero',
    audit: {
      fundingInRange: true,
      fundingAmountUSD: 4500000,
      fundingDisplay: '$4.5M (Series A / Seed Extension)',
      fundingType: 'Series A',
      isTechPlatform: true,
      techCategory: 'Cross-Border Payments & Digital Wallet Platform',
      minimalUSPresence: true,
      headquarters: 'Abu Dhabi Global Market (ADGM), UAE',
      country: 'United Arab Emirates',
      usPresenceDetail: 'Zero US operations; holds regulatory licenses under Abu Dhabi ADGM & Central Bank of the UAE.',
      executiveVerified: true,
      executiveName: 'Kevin Kilty',
      executiveRole: 'CEO & Founder',
      verifiedEmail: 'kevin@hubpay.app',
      emailConfidence: 'High',
      overallMatch: true,
      tvbOrbit: 'Fintech & Payments',
      tvbHub: 'UAE Hub (Dubai/Abu Dhabi)',
      tvbStrategicFitReason: 'Matches TVB UAE Hub and Fintech & Payments Orbit. Can expand through TVB UK and India Hub corridors.',
      notes: 'Licensed FinTech platform in UAE, within $1M-$5M funding bracket.'
    },
    discoveredAt: '2026-03-10T09:30:00.000Z',
    sourceOrigin: 'Hub71 Abu Dhabi Portfolio & DIFC FinTech Hive',
    tags: ['Fintech Orbit', 'UAE Hub', 'Cross-Border Payments', 'Remittance']
  },
  {
    id: 'tvb-comp-09',
    name: 'Travefy EU / Wayfarer Platform',
    website: 'https://wayfarerops.io',
    description: 'White-label itinerary distribution and inventory management SaaS engine for independent European tour operators.',
    industry: 'Travel & Mobility Technology',
    tvbOrbit: 'Travel & Mobility',
    tvbHub: 'Continental Europe',
    country: 'Spain',
    city: 'Barcelona',
    foundedYear: 2021,
    fundingDisplay: '$2.4M USD',
    fundingAmountUSD: 2400000,
    revenueOrFunding: 'Funding',
    executiveName: 'Marta Soler',
    executiveRole: 'Co-Founder & CEO',
    verifiedEmail: 'marta.soler@wayfarerops.io',
    executiveLinkedIn: 'linkedin.com/in/martasolertravel',
    usPresence: 'Zero',
    audit: {
      fundingInRange: true,
      fundingAmountUSD: 2400000,
      fundingDisplay: '$2.4M (€2.2M Seed)',
      fundingType: 'Seed',
      isTechPlatform: true,
      techCategory: 'White-Label Travel Infrastructure Platform',
      minimalUSPresence: true,
      headquarters: 'Barcelona, Spain',
      country: 'Spain',
      usPresenceDetail: 'No US presence or entities; focused purely on Southern European and Mediterranean travel distributors.',
      executiveVerified: true,
      executiveName: 'Marta Soler',
      executiveRole: 'Co-Founder & CEO',
      verifiedEmail: 'marta.soler@wayfarerops.io',
      emailConfidence: 'High',
      overallMatch: true,
      tvbOrbit: 'Travel & Mobility',
      tvbHub: 'Continental Europe',
      tvbStrategicFitReason: 'Direct alignment with TVB Travel Orbit (white-label travel infrastructure, payments and cards, distribution).',
      notes: 'Fits Travel Orbit requirements from TVB overview.'
    },
    discoveredAt: '2026-03-10T12:00:00.000Z',
    sourceOrigin: 'Barcelona Tech City & South Summit Travel Cohort',
    tags: ['Travel Orbit', 'Continental Europe', 'TravelTech', 'White-label SaaS']
  },
  {
    id: 'tvb-comp-10',
    name: 'Veloce Robotics',
    website: 'https://velocerobotics.com',
    description: 'Autonomous intralogistics robotics and fleet orchestration platform for mid-sized automated fulfillment hubs.',
    industry: 'Robotics & AI Automation',
    tvbOrbit: 'AI & Automation',
    tvbHub: 'Singapore/SE Asia Hub',
    country: 'Singapore',
    city: 'Singapore',
    foundedYear: 2022,
    fundingDisplay: '$3.5M USD',
    fundingAmountUSD: 3500000,
    revenueOrFunding: 'Funding',
    executiveName: 'Wei Jian Tan',
    executiveRole: 'CEO & Co-Founder',
    // Example of strictly verified email:
    verifiedEmail: 'weijian.tan@velocerobotics.com',
    executiveLinkedIn: 'linkedin.com/in/weijiantan-sg',
    usPresence: 'Minimal',
    audit: {
      fundingInRange: true,
      fundingAmountUSD: 3500000,
      fundingDisplay: '$3.5M (Pre-Series A / SGInnovate)',
      fundingType: 'Pre-Series A',
      isTechPlatform: true,
      techCategory: 'Fleet Orchestration AI Platform',
      minimalUSPresence: true,
      headquarters: 'Singapore',
      country: 'Singapore',
      usPresenceDetail: 'Singapore headquarters and manufacturing assembly in Johor; no permanent US sales or distribution footprint.',
      executiveVerified: true,
      executiveName: 'Wei Jian Tan',
      executiveRole: 'CEO & Co-Founder',
      verifiedEmail: 'weijian.tan@velocerobotics.com',
      emailConfidence: 'High',
      overallMatch: true,
      tvbOrbit: 'AI & Automation',
      tvbHub: 'Singapore/SE Asia Hub',
      tvbStrategicFitReason: 'Strong scaleup targeting global expansion; TVB Austin Hub can act as US bridge for pilot deployments.',
      notes: 'Hardware-enabled software platform matching TVB target criteria.'
    },
    discoveredAt: '2026-03-10T15:20:00.000Z',
    sourceOrigin: 'SGInnovate Deep Tech Directory & Enterprise Singapore Cohort',
    tags: ['AI Orbit', 'SE Asia Hub', 'Autonomous Fleet', 'Industrial AI']
  },
  {
    id: 'tvb-comp-11',
    name: 'HookMhealth Data',
    website: 'https://hookmhealth.org',
    description: 'Decentralized health data consent, governance, and closed-loop referral protocol for regional healthcare networks.',
    industry: 'Healthcare Trust & Governance',
    tvbOrbit: 'Healthcare',
    tvbHub: 'UK Hub (London/UK)',
    country: 'United Kingdom',
    city: 'Manchester',
    foundedYear: 2022,
    fundingDisplay: '$1.4M USD',
    fundingAmountUSD: 1400000,
    revenueOrFunding: 'Funding',
    executiveName: 'Alastair Vance',
    executiveRole: 'Co-Founder & CEO',
    // Strictly unverified email left blank per requirement:
    verifiedEmail: '',
    executiveLinkedIn: 'linkedin.com/in/alastairvance-uk',
    usPresence: 'Zero',
    audit: {
      fundingInRange: true,
      fundingAmountUSD: 1400000,
      fundingDisplay: '$1.4M (£1.1M Pre-Seed & NHS Grant)',
      fundingType: 'Seed',
      isTechPlatform: true,
      techCategory: 'Health Data Consent & Trust Infrastructure',
      minimalUSPresence: true,
      headquarters: 'Manchester, UK',
      country: 'United Kingdom',
      usPresenceDetail: 'Deployed exclusively across UK NHS regional health partnerships; zero US activity.',
      executiveVerified: true,
      executiveName: 'Alastair Vance',
      executiveRole: 'Co-Founder & CEO',
      verifiedEmail: '',
      emailConfidence: 'Unverified (Blank)',
      overallMatch: false, // Flagged because email is unverified (per requirement: Name & email of CEO or Co-founder must be available)
      tvbOrbit: 'Healthcare',
      tvbHub: 'UK Hub (London/UK)',
      tvbStrategicFitReason: 'Explicitly named in TVB Healthcare Orbit overview as trust layer initiative. Pending verified founder email address to achieve full pass.',
      notes: 'Unverified email is left blank in strict adherence to user rules: "For all fields that are unverified/untrue, it is advisable to leave the field blank and not put any generic information."'
    },
    discoveredAt: '2026-03-10T17:00:00.000Z',
    sourceOrigin: 'TVB Healthcare Orbit Reference Document & NHS Innovation Accelerator',
    tags: ['Healthcare Orbit', 'UK Hub', 'Trust Layer', 'Needs Email Verification']
  }
];
